### ISSUE TITLE
Incorrect Trackable name being displayed on InputContainerView

### ISSUE THREAD

**Issue by squiggie** [Flaredown/FlaredownAndroid#37]
The trackable's id's aren't unique. So when they get stored in Realm and then queried back out, if two trackables, a symptom and treatment, have the same id, it will only pull the first one from Realm. This may or may not be the correct meta. 

Subsequently, the wrong metatrackable is attacked to the trackable and wrong information is displayed on the containerview.

**Comment by thunter1000** [comment]
The ID of `MetaTrackables` are not unique across type. This causes the trackables to get mixed up when loaded from the cache.

To resolve the issue a composite key is used combining the `id` and `TrackableType`.
