### ISSUE TITLE
Add global nav bar at the bottom of activities.

### ISSUE THREAD

**Issue by thunter1000** [Flaredown/FlaredownAndroid#47]
Navigation bar should be applied to all activities, allowing for easy navigation between the check in, graph and account. Also the design may change over time, so make it flexible.  Sample: https://flaredownteam.slack.com/files/loganmerriam/F1J5HSF0E/screenshot_2016-06-18_12.46.22.png

**Comment by squiggie** [comment]
Link doesn't seem to work.

**Comment by thunter1000** [comment]
Sorry my bad @squiggie , I think because it was sent directly via slack you don't have the perms let me try uploading. 

<img width="257" alt="screenshot_2016-06-18_12 46 22" src="https://cloud.githubusercontent.com/assets/11636649/16689964/72797216-451d-11e6-80d2-87b446d615e3.png"> <img width="303" alt="screenshot 2016-06-18 12 47 23" src="https://cloud.githubusercontent.com/assets/11636649/16690007/9f826286-451d-11e6-8f15-a3b2240e67fb.png">

**Comment by squiggie** [comment]
Added BottomBar library for global navigation in commit 596e6382a4ea668d29623b1cdc1a4d93c787b92e
